export { default as AdminAdministrationPage } from "./AdminAdministrationPage";
export { default as AdminConsoleLayout } from "./AdminConsoleLayout";
export { default as AdminDataPage } from "./AdminDataPage";
export { default as AdminMyAccountPage } from "./AdminMyAccountPage";
export { default as AdminProjectsPage } from "./AdminProjectsPage";
export { default as AdminSettingsPage } from "./AdminSettingsPage";
export { default as InstitutionalProjectsPage } from "../InstitutionalProjectsPage";
export { default as TemplatesPage } from "./TemplatesPage";
export { default as AnalyticsPage } from "./AnalyticsPage";
